#!/bin/bash

# if used doesn't work properly :-/

if [ ! -z $mayalinuxDebug ] ; then echo -e "Looking for unwanted cd" >&2 ; fi

destionation="$(pwd)"
if [ ! ${#destionation} -ge ${#player_path} -o ! "${destionation:0:${#player_path}}" = "$player_path" ]
  then
    cd - > /dev/null
    cat $data_path/implementations/$lang/commons/cd.txt
fi

